import test from 'node:test';
import assert from 'node:assert/strict';
import {mat4Mul,mat4Inverse,transform,mat4Identity,pointTransform,perspective,orthographic,lookAt,frameMatrix,rng,sub,length} from '../src/math.js';
import {RailNetwork,RailCursor,TrackEdge} from '../src/tracks.js';
import {Train,Traffic,Mission,makeStations} from '../src/physics.js';
import {WORLDS,STOCK} from '../src/data.js';
import {validateProject,encodeProject} from '../src/persistence.js';
import {RailwayWorld} from '../src/world.js';
const near=(actual,expected,tolerance=1e-4)=>assert.ok(Math.abs(actual-expected)<tolerance,`${actual} != ${expected} ±${tolerance}`);
const env={weather:'clear',electrified:true};
const net=()=>new RailNetwork(WORLDS[0]);
const run=(t,seconds,environment=env,options={safety:false})=>{for(let i=0;i<seconds*60;i++)t.step(1/60,environment,options);};
function flatNet(){const n=net();for(const e of n.edges.values()){e.points=e.points.map(p=>[p[0],80,p[2]]);n.edges.set(e.id,new TrackEdge(e.id,e.points,300));}return n;}
function releasedTrain(stock=STOCK[0],network=flatNet()){const t=new Train(network,stock);t.controls.brake=0;t.cylinders.fill(0);return t;}

test('column-major matrix inversion and multiplication',()=>{const m=transform([103,22,-57],[2,3,.7],.8,.3,.2),v=mat4Mul(m,mat4Inverse(m));v.forEach((x,i)=>near(x,mat4Identity()[i],3e-5));});
test('local frame follows its forward vector',()=>{const m=frameMatrix([1,2,3],[0,0,1]);assert.deepEqual(pointTransform(m,[2,3,4]),[3,5,7]);});
test('WebGPU and WebGL perspective depth conventions',()=>{for(const gpu of [true,false]){const p=perspective(1,1.5,.2,100,gpu);const z=d=>(p[10]*-d+p[14])/d;near(z(.2),gpu?0:-1,1e-6);near(z(100),1,1e-6);}});
test('orthographic near and far depth',()=>{for(const gpu of [true,false]){const p=orthographic(-2,2,-2,2,1,50,gpu);near(pointTransform(p,[0,0,-1])[2],gpu?0:-1,1e-6);near(pointTransform(p,[0,0,-50])[2],1,1e-6);}});
test('random worlds are reproducible',()=>{const a=rng(42),b=rng(42);for(let i=0;i<1000;i++)assert.equal(a(),b());});
test('all eight world networks contain finite continuous rail geometry',()=>{for(const world of WORLDS){const n=new RailNetwork(world);assert.equal(n.edges.size,4);assert.ok(n.totalLength>5000);for(const edge of n.edges.values()){assert.ok(edge.length>100);for(const p of edge.points)assert.ok(p.every(Number.isFinite));for(const next of ['approach'].includes(edge.id)?['main','branch']:[n.next(edge.id)])near(length(sub(edge.at(edge.length).p,n.edges.get(next).at(0).p)),0,.01);}}});
test('cursor crosses turnout and retains car route history',()=>{const n=net(),a=n.edges.get('approach');n.switchBranch=true;const c=new RailCursor(n,'approach',a.length-10);c.advance(40);assert.equal(c.edge,'branch');near(c.s,30);assert.equal(c.pose(-40).edge,'approach');n.switchBranch=false;assert.equal(c.edge,'branch');assert.equal(c.pose(-10).edge,'branch');c.advance(-40);assert.equal(c.edge,'approach');near(c.s,a.length-10);});
test('cursor traverses many laps with bounded history',()=>{const n=net(),c=new RailCursor(n);for(let i=0;i<20000;i++)c.advance(23);assert.ok(c.path.length<35);assert.ok(c.s>=0&&c.s<=n.edges.get(c.edge).length);assert.ok(c.pose(-15000).p.every(Number.isFinite));});
test('snapshot and restore preserve exact cursor position',()=>{const n=net(),a=new RailCursor(n);a.advance(13530);const b=new RailCursor(n);b.restore(JSON.parse(JSON.stringify(a.snapshot())));assert.deepEqual(a.snapshot(),b.snapshot());});
test('spatial index resolves nearest rail sample',()=>{const n=net(),p=n.edges.get('main').at(310),q=n.nearest(p.p[0]+p.right[0]*3,p.p[2]+p.right[2]*3);assert.equal(q.edge,'main');near(q.distance,3,.2);near(q.s,310,.5);});
test('train accelerates under traction and consumes energy',()=>{const t=releasedTrain();t.controls.throttle=.8;run(t,25);assert.ok(t.speed>5);assert.ok(t.cursor.odometer>20);assert.ok(t.energy>0);assert.ok(t.traction>0);});
test('air brake pipe applies progressively and releases at a bounded rate',()=>{const t=releasedTrain();t.controls.brake=1;run(t,1);near(t.pipe,3.85,.02);assert.ok(t.cylinders[0]>0);assert.ok(t.cylinders.at(-1)<=t.cylinders[0]);run(t,5);assert.ok(t.pipe<.05);t.controls.brake=0;run(t,5);assert.ok(t.pipe<2.2&&t.pipe>2);run(t,10);near(t.pipe,5);});
test('emergency brake stops a moving train and latches',()=>{const t=releasedTrain();t.speed=22;t.emergency();run(t,30);assert.ok(Math.abs(t.speed)<.03);assert.equal(t.controls.emergency,true);t.resetEmergency();assert.equal(t.controls.emergency,false);});
test('doors and reverser interlock while moving',()=>{const t=releasedTrain();t.speed=10;assert.throws(()=>t.toggleDoors());assert.throws(()=>t.setReverser(-1));assert.throws(()=>t.setCars(5));assert.throws(()=>t.setStock(STOCK[1]));});
test('doors, pantograph, master and unpowered route prevent traction',()=>{for(const mode of ['doors','pantograph','master','supply']){const t=releasedTrain();t.controls.throttle=1;if(mode==='doors')t.controls.doors=true;else if(mode==='pantograph')t.controls.pantograph=false;else if(mode==='master')t.controls.master=false;run(t,8,{...env,electrified:mode!=='supply'});near(t.traction,0);near(t.speed,0);}});
test('wet rails reduce available tractive effort; sanding improves it',()=>{const stock={...STOCK[0],tractive:500000,power:8e6};const dry=releasedTrain(stock),wet=releasedTrain(stock),sand=releasedTrain(stock);for(const t of [dry,wet,sand])t.controls.throttle=1;sand.controls.sand=true;run(dry,4);run(wet,4,{weather:'rain'});run(sand,4,{weather:'rain'});assert.ok(dry.traction>wet.traction);assert.ok(sand.traction>wet.traction);assert.ok(wet.wheelslip>0);});
test('reverse traction causes signed reverse rail motion',()=>{const t=releasedTrain();t.setReverser(-1);t.controls.throttle=.5;const initial=t.cursor.s;run(t,15);assert.ok(t.speed< -2);assert.ok(t.cursor.s<initial);});
test('fixed-step trajectory is deterministic',()=>{const a=releasedTrain(),b=releasedTrain();a.controls.throttle=b.controls.throttle=.62;run(a,30);run(b,30);assert.deepEqual(a.snapshot(),b.snapshot());});
test('invalid time steps are rejected',()=>{const t=releasedTrain();for(const dt of [0,-1,.2,Infinity,NaN])assert.throws(()=>t.step(dt,env));});
test('whole consist occupies blocks and signals detect another train',()=>{const n=flatNet(),a=releasedTrain(STOCK[0],n),b=new Train(n,STOCK[0],'ai','approach',750),traffic=new Traffic(n);traffic.update([a,b]);assert.ok(traffic.occupied.size>1);assert.ok(traffic.dangerDistance(a)<600);assert.equal(traffic.aspect('approach',550,'player'),'red');traffic.update([a]);assert.equal(traffic.dangerDistance(a),Infinity);});
test('dispatch signal hold and turnout protection are operational',()=>{const n=net(),t=new Train(n),traffic=new Traffic(n);traffic.update([t]);traffic.holds.add(traffic.block(t.cursor.pose(200)));assert.ok(Number.isFinite(traffic.dangerDistance(t)));t.cursor=new RailCursor(n,'approach',n.edges.get('approach').length-20);assert.equal(traffic.switchLocked([t]),true);});
test('passenger mission rewards a completed station dwell',()=>{const n=flatNet(),t=releasedTrain(STOCK[0],n),m=new Mission('passenger'),stations=makeStations(n,WORLDS[0]);t.controls.doors=true;for(let i=0;i<1260;i++)m.step(1/60,t,stations,120);assert.equal(m.stops,1);assert.ok(m.score>1000);assert.equal(m.stopLog.length,1);});
test('project validation rejects malformed, unsupported and excessive data',()=>{assert.throws(()=>validateProject({}));assert.throws(()=>validateProject({format:'railbound-adventures',version:5}));const app={world:{def:WORLDS[0],editor:{seed:1},network:net()},player:releasedTrain(),trains:[],mission:new Mission(),env,settings:{},camera:{mode:'chase'}};app.trains=[app.player];const obj=encodeProject(app);assert.equal(validateProject(obj).world,'alpine');obj.editor.objects=Array(1501).fill({});assert.throws(()=>validateProject(obj));});
test('project serialization restores train and controls',()=>{const n=net(),t=new Train(n,STOCK[3]);t.controls.throttle=.71;run(t,3);const o=t.snapshot(),other=new Train(n);other.restore(JSON.parse(JSON.stringify(o)));assert.equal(other.stock.id,'heritage');near(other.speed,t.speed);near(other.controls.throttle,.71);assert.equal(other.cars,t.cars);});
test('terrain brushes and custom track nodes change real world geometry',()=>{const w=new RailwayWorld(WORLDS[0]),base=w.baseHeight(0,0),edit=new RailwayWorld(WORLDS[0],{heightEdits:[{x:0,z:0,radius:90,delta:25}]});near(edit.baseHeight(0,0)-base,25);const points=[{x:-600,y:50,z:-600},{x:600,y:55,z:-600},{x:600,y:60,z:600},{x:-600,y:55,z:600}];const custom=new RailwayWorld(WORLDS[0],{customTrack:points});assert.ok(custom.network.totalLength<w.network.totalLength);assert.equal(custom.network.controls.length,4);});

test('AI departs after a station dwell rather than repeatedly reopening doors',()=>{const n=flatNet(),t=releasedTrain(STOCK[0],n),traffic=new Traffic(n),stations=makeStations(n,WORLDS[0]);t.ai=true;const start=t.cursor.s;for(let i=0;i<90*60;i++){traffic.update([t]);traffic.controlAI(t,1/60,stations,env);t.step(1/60,env,{safety:true,limit:140,danger:traffic.dangerDistance(t)});}assert.ok(t.cursor.odometer>80,`Only moved ${t.cursor.odometer} m`);assert.ok(!t.derailed);});
test('collision intervals distinguish overlapping and separated train consists',()=>{const n=flatNet(),a=new Train(n,STOCK[0],'player','approach',300),b=new Train(n,STOCK[0],'ai','approach',330),traffic=new Traffic(n);traffic.update([a,b]);assert.equal(traffic.contacts().length,1);b.cursor.advance(300);traffic.update([a,b]);assert.equal(traffic.contacts().length,0);});
test('door and emergency power cuts are immediate even with traction lag',()=>{const t=releasedTrain();t.controls.throttle=1;run(t,5);assert.ok(t.traction>0);t.emergency();t.step(1/60,env,{safety:false});near(t.traction,0);});
test('invalid cursor connectivity and nonfinite odometers are contained',()=>{const n=net(),c=new RailCursor(n);assert.throws(()=>c.restore({path:['main','branch'],index:1,s:10}));c.restore({path:['return','approach'],index:1,s:10,odometer:Infinity});assert.equal(c.odometer,0);});
