/** Procedural, speed/load-dependent rail audio. No media downloads or autoplay assumptions. */
export class RailAudio {
 constructor(){this.enabled=false;this.context=null;this.volume=.36;this.horning=false;}
 async enable(){if(!this.context){const C=globalThis.AudioContext||globalThis.webkitAudioContext;if(!C)return;const c=this.context=new C();this.master=c.createGain();this.master.gain.value=0;this.master.connect(c.destination);this.motor=c.createOscillator();this.motor.type='sawtooth';this.motorGain=c.createGain();this.motorFilter=c.createBiquadFilter();this.motorFilter.type='lowpass';this.motorFilter.frequency.value=150;this.motor.connect(this.motorFilter).connect(this.motorGain).connect(this.master);this.motor.start();const n=c.createBuffer(1,c.sampleRate*2,c.sampleRate),a=n.getChannelData(0);let last=0;for(let i=0;i<a.length;i++){last=(last+Math.random()*.18-.09)*.985;a[i]=last;}this.noise=c.createBufferSource();this.noise.buffer=n;this.noise.loop=true;this.railFilter=c.createBiquadFilter();this.railFilter.type='bandpass';this.railFilter.frequency.value=650;this.railFilter.Q.value=.6;this.railGain=c.createGain();this.noise.connect(this.railFilter).connect(this.railGain).connect(this.master);this.noise.start();this.hornGain=c.createGain();this.hornGain.gain.value=0;this.hornGain.connect(this.master);this.horns=[185,233,277].map(f=>{const o=c.createOscillator();o.type='triangle';o.frequency.value=f;o.connect(this.hornGain);o.start();return o;});}await this.context.resume();this.enabled=true;this.master.gain.setTargetAtTime(this.volume,this.context.currentTime,.1);}
 toggle(){if(this.enabled){this.enabled=false;this.master?.gain.setTargetAtTime(0,this.context.currentTime,.05);}else return this.enable();}
 horn(on){this.horning=on;if(this.context)this.hornGain.gain.setTargetAtTime(on?.2:0,this.context.currentTime,.035);}
 update(train,weather,paused){if(!this.context)return;const t=this.context.currentTime,v=Math.abs(train.speed),c=train.controls,steam=train.stock.kind==='steam';this.master.gain.setTargetAtTime(this.enabled&&!paused?this.volume:0,t,.08);this.motor.frequency.setTargetAtTime(steam?40+v*3:35+v*4+c.throttle*25,t,.15);this.motorFilter.frequency.setTargetAtTime(steam?170:170+v*13+c.throttle*150,t,.15);this.motorGain.gain.setTargetAtTime(c.master?(steam?.022+Math.max(0,Math.sin(train.cursor.odometer*2))*.09:.028+c.throttle*.07):0,t,.12);this.railGain.gain.setTargetAtTime(Math.min(.48,v*.009)+(weather==='rain'||weather==='storm'?.10:0),t,.12);this.railFilter.frequency.setTargetAtTime(350+v*21,t,.15);}
 stop(){this.horn(false);if(this.context)this.master.gain.setTargetAtTime(0,this.context.currentTime,.01);}
}
