import {add,sub,mul,norm,mix3,clamp,cross,frameMatrix,pointTransform} from './math.js';
export const CAMERA_MODES=['cab','chase','orbit','aerial','trackside','free'];
export class CameraRig {
 constructor(){this.mode='chase';this.position=[0,100,0];this.target=[0,60,0];this.distance=90;this.azimuth=-.87;this.elevation=.28;this.fov=56;this.initial=true;this.cabYaw=0;this.cabPitch=0;this.trackAnchor=null;this.freeYaw=0;this.freePitch=0;this.photoOrbit=false;}
 setMode(mode){if(!CAMERA_MODES.includes(mode))return;this.mode=mode;this.initial=true;this.trackAnchor=null;if(mode==='aerial')this.distance=480;else if(mode==='chase'||mode==='orbit')this.distance=90;if(mode==='free'){const f=norm(sub(this.target,this.position));this.freeYaw=Math.atan2(f[0],f[2]);this.freePitch=Math.asin(f[1]);}}
 rotate(dx,dy){if(this.mode==='cab'){this.cabYaw=clamp(this.cabYaw-dx*.004,-1.55,1.55);this.cabPitch=clamp(this.cabPitch-dy*.003,-.6,.6);}else if(this.mode==='free'){this.freeYaw-=dx*.004;this.freePitch=clamp(this.freePitch-dy*.003,-1.5,1.5);}else{this.azimuth-=dx*.005;this.elevation=clamp(this.elevation+dy*.004,.055,1.48);}}
 zoom(delta){if(this.mode==='cab'){this.fov=clamp(this.fov+delta*.02,38,90);return;}this.distance=clamp(this.distance*Math.exp(delta*.001),10,2200);}
 update(train,world,dt,keys){const p=train.cursor.pose(),pose=train.cursor.pose((globalThis.innerWidth/globalThis.innerHeight||1.6)<.75?-2:-Math.min(train.length*.25,40)),f=p.f,right=p.right;let eye,aim;
  if(this.mode==='free'){const dir=[Math.sin(this.freeYaw)*Math.cos(this.freePitch),Math.sin(this.freePitch),Math.cos(this.freeYaw)*Math.cos(this.freePitch)],r=norm(cross([0,1,0],dir));const speed=(keys?.has('ShiftLeft')?180:38)*dt;for(const [key,vec]of [['KeyW',dir],['KeyS',mul(dir,-1)],['KeyD',r],['KeyA',mul(r,-1)],['KeyE',[0,1,0]],['KeyQ',[0,-1,0]]])if(keys?.has(key))this.position=add(this.position,mul(vec,speed));this.target=add(this.position,mul(dir,50));return;}
  if(this.mode==='cab'){eye=add(add(p.p,mul(f,train.stock.kind==='steam'?-3:train.stock.locoLength*.34)),[0,3.78,0]);eye=add(eye,mul(right,-.45));const look=norm(add(add(mul(f,Math.cos(this.cabYaw)),mul(right,Math.sin(this.cabYaw))),[0,this.cabPitch,0]));aim=add(eye,mul(look,90));const vibration=Math.min(Math.abs(train.speed)/35,1)*.01;eye[1]+=Math.sin(train.cursor.odometer*1.7)*vibration;this.position=eye;this.target=aim;this.initial=false;return;}
  if(this.mode==='trackside'){if(!this.trackAnchor||Math.hypot(...sub(this.trackAnchor,p.p))>210){const ahead=train.cursor.pose(100);this.trackAnchor=add(add(ahead.p,mul(ahead.right,-20)),[0,4,0]);}eye=this.trackAnchor;aim=add(p.p,[0,2.5,0]);}
  else{if(this.photoOrbit&&this.mode==='orbit')this.azimuth+=dt*.12;aim=add(pose.p,[0,2.4,0]);const el=this.mode==='aerial'?Math.max(.8,this.elevation):this.elevation;const horizontal=this.distance*Math.cos(el);eye=add(add(add(aim,mul(right,Math.sin(this.azimuth)*horizontal)),mul(f,Math.cos(this.azimuth)*horizontal)),[0,Math.sin(el)*this.distance,0]);const ground=world.height(eye[0],eye[2]);eye[1]=Math.max(eye[1],ground+2.5,world.def.water+3);}
  const alpha=this.initial?1:1-Math.exp(-dt*(this.mode==='chase'?4.8:7));this.position=mix3(this.position,eye,alpha);this.target=mix3(this.target,aim,alpha);this.initial=false;
 }
}
