import {generationOptions} from './generation.js';
import {WORLDS,STOCK,WEATHER,SCENARIOS} from './data.js';
import {clamp} from './math.js';
export const SAVE_KEY='railbound-adventures-simulation-v2';
export function storageGet(key){try{return localStorage.getItem(key);}catch{return null;}}
export function storageSet(key,value){try{localStorage.setItem(key,value);return true;}catch{return false;}}
function finite(n,a,b,fallback=0){return Number.isFinite(n)?clamp(n,a,b):fallback;}
function array(v,max){if(v==null)return [];if(!Array.isArray(v)||v.length>max)throw new Error('Project contains too many items or an invalid list.');return v;}
export function validateProject(value){if(!value||typeof value!=='object'||value.format!=='railbound-adventures'||value.version!==2)throw new Error('Not a supported Railbound Adventures v2 project.');const world=WORLDS.find(w=>w.id===value.world);if(!world)throw new Error('Unknown world.');if(!value.player||!STOCK.some(s=>s.id===value.player.stock))throw new Error('Invalid player train.');const editor=value.editor||{};const clean={generationVersion:editor.generationVersion===3?3:2,generation:generationOptions(editor.generation),seed:finite(editor.seed,1,2147483647,world.seed),electrified:editor.electrified!==false,objects:array(editor.objects,1500).map(o=>({type:['tree','building','rock'].includes(o.type)?o.type:'tree',x:finite(o.x,-12000,12000),z:finite(o.z,-12000,12000),size:finite(o.size,3,60,18),rotation:finite(o.rotation,-Math.PI*2,Math.PI*2)})),heightEdits:array(editor.heightEdits,250).map(o=>({x:finite(o.x,-12000,12000),z:finite(o.z,-12000,12000),radius:finite(o.radius,10,600,90),delta:finite(o.delta,-200,200,0)})),stations:array(editor.stations,50).map(o=>({edge:['approach','main','branch','return'].includes(o.edge)?o.edge:'approach',s:finite(o.s,0,100000),name:String(o.name||'New station').slice(0,64)})),customTrack:null};
 if(editor.customTrack!=null){clean.customTrack=array(editor.customTrack,150).map(o=>({x:finite(o.x,-6000,6000),y:finite(o.y,0,900,world.railY),z:finite(o.z,-6000,6000)}));const routeLength=clean.customTrack.reduce((sum,p,i)=>{const q=clean.customTrack[(i+1)%clean.customTrack.length];return sum+Math.hypot(p.x-q.x,p.y-q.y,p.z-q.z);},0);if(routeLength>75000)throw new Error('Custom routes are limited to 75 km of control-point length.');if(clean.customTrack.length<4)throw new Error('Custom track requires at least four control points.');for(let i=0;i<clean.customTrack.length;i++){const a=clean.customTrack[i],b=clean.customTrack[(i+1)%clean.customTrack.length];if(Math.hypot(a.x-b.x,a.z-b.z)<25)throw new Error('Adjacent track nodes must be at least 25 metres apart.');}}
 const env=value.env||{};const settings=value.settings||{};const result={...value,world:world.id,editor:clean,ai:array(value.ai,5),env:{hour:finite(env.hour,0,23.999,world.hour),weather:Object.hasOwn(WEATHER,env.weather)?env.weather:'clear',timeRate:finite(env.timeRate,0,240,4),exposure:finite(env.exposure,.5,1.8,1),electrified:clean.electrified},settings:{quality:['low','medium','high','ultra'].includes(settings.quality)?settings.quality:'high',resolution:finite(settings.resolution,.5,1,1),shadows:settings.shadows!==false,adaptive:settings.adaptive!==false,safety:settings.safety!==false,units:settings.units==='mph'?'mph':'km/h',volume:finite(settings.volume,0,1,.36),timeScale:finite(settings.timeScale,.25,4,1),gamepad:settings.gamepad!==false},simTime:finite(value.simTime,0,1e10,0),paused:!!value.paused,dispatch:{autopilot:!!value.dispatch?.autopilot,holds:array(value.dispatch?.holds,500).filter(s=>typeof s==='string'&&/^(approach|main|branch|return):[0-9]{1,5}$/.test(s))},cameraState:typeof value.cameraState==='object'&&value.cameraState?value.cameraState:{},scenario:SCENARIOS.some(s=>s.id===value.scenario)?value.scenario:'free'};return result;}
export function encodeProject(app){return {format:'railbound-adventures',version:2,savedAt:new Date().toISOString(),world:app.world.def.id,editor:structuredClone(app.world.editor),env:{...app.env},settings:{...app.settings},scenario:app.mission.mode,mission:{score:app.mission.score,stops:app.mission.stops,boarded:app.mission.boarded,lastId:app.mission.lastId,complete:app.mission.complete,targetId:app.mission.target?.id||null,dwell:app.mission.dwell,penaltyClock:app.mission.penaltyClock,message:app.mission.message,stopLog:app.mission.stopLog},player:app.player.snapshot(),ai:app.trains.filter(t=>t!==app.player).map(t=>t.snapshot()),switchBranch:app.world.network.switchBranch,camera:app.camera.mode,cameraState:{distance:app.camera.distance,azimuth:app.camera.azimuth,elevation:app.camera.elevation,cabYaw:app.camera.cabYaw,cabPitch:app.camera.cabPitch,fov:app.camera.fov},simTime:app.simTime||0,paused:!!app.paused,dispatch:{holds:[...(app.world.traffic?.holds||[])],autopilot:!!app.autopilot}};}
