import {AuthoredLibrary} from './authored-assets.js';
import {SurfaceLibrary} from './materials.js';
import {stabilizedShadow,SHADOW_EXTENTS,shadowCascadeCount} from './shadow-cascades.js';
import {PostProcessor,targetSize} from './postprocess.js';
import {mat4Mul,mat4Inverse,perspective,lookAt,orthographic,add,mul,norm,sub,length,dot,hex,clamp,smooth} from './math.js';
import {WEATHER} from './data.js';
import {WGSL_MAIN,WGSL_SKY,WGSL_SHADOW,GLSL_MAIN_VS,GLSL_MAIN_FS,GLSL_SKY_VS,GLSL_SKY_FS,GLSL_SHADOW_VS,GLSL_SHADOW_FS} from './shaders.js';
const VERTEX_LAYOUT=[{arrayStride:32,attributes:[{shaderLocation:0,offset:0,format:'float32x3'},{shaderLocation:1,offset:12,format:'float32x3'},{shaderLocation:2,offset:24,format:'float32x2'}]},{arrayStride:96,stepMode:'instance',attributes:Array.from({length:6},(_,i)=>({shaderLocation:3+i,offset:i*16,format:'float32x4'}))}];
export class Renderer {
 constructor(canvas,onError=console.error){this.canvas=canvas;this.onError=onError;this.kind='Starting';this.frame=new Float32Array(124);this.drawCalls=0;this.triangles=0;this.shadowSize=1536;this.width=0;this.height=0;this.samples=4;this.lost=false;this.geometries=new Set();this.batches=new Set();this.settings={quality:'high',shadows:true,resolution:1};this.lastError=null;this.post=new PostProcessor();this.sceneFormat='rgba16float';this.materials=new SurfaceLibrary();this.authored=new AuthoredLibrary();}
 async initialize(forceGL=false){if(!forceGL&&navigator.gpu&&globalThis.isSecureContext){try{await this.initGPU();return;}catch(e){console.warn('WebGPU initialization failed; trying WebGL 2.',e);this.lastError=e.message;if(this.device){this.device.destroy();this.device=null;}if(this.context){this.context.unconfigure();const next=this.canvas.cloneNode();this.canvas.replaceWith(next);this.canvas=next;this.context=null;}}this.post.dispose();this.post=new PostProcessor();this.materials.dispose();this.materials=new SurfaceLibrary();this.authored.dispose();this.authored=new AuthoredLibrary();}await this.initGL();}
 async initGPU(){const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)throw new Error('No WebGPU adapter available.');this.device=await adapter.requestDevice();const d=this.device;this.device.lost.then(info=>{if(info.reason==='destroyed')return;this.lost=true;this.onError(`Graphics device lost: ${info.message||info.reason}. Reload to recover.`);});d.addEventListener('uncapturederror',e=>{console.error(e.error);this.onError(e.error.message);});this.context=this.canvas.getContext('webgpu');if(!this.context)throw new Error('WebGPU canvas context unavailable');this.format=navigator.gpu.getPreferredCanvasFormat();this.context.configure({device:d,format:this.format,alphaMode:'opaque'});await this.post.initGPU(d,this.format);await Promise.all([this.materials.initialize(d,null),this.authored.initialize(d,null)]);
  this.uniform=d.createBuffer({size:this.frame.byteLength,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});
  this.shadowTexture=d.createTexture({size:[this.shadowSize,this.shadowSize,3],format:'depth32float',usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.TEXTURE_BINDING});this.shadowArrayView=this.shadowTexture.createView({dimension:'2d-array'});this.shadowViews=[0,1,2].map(i=>this.shadowTexture.createView({dimension:'2d',baseArrayLayer:i,arrayLayerCount:1}));this.shadowView=this.shadowViews[1];this.sampler=d.createSampler({compare:'less-equal',magFilter:'linear',minFilter:'linear'});
  const basicLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}}]});
  const shadowLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}},{binding:6,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'float',viewDimension:'2d-array'}},{binding:8,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'filtering'}}]});
  const mainLayout=d.createBindGroupLayout({entries:[{binding:0,visibility:GPUShaderStage.VERTEX|GPUShaderStage.FRAGMENT,buffer:{type:'uniform'}},{binding:1,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'depth',viewDimension:'2d-array'}},{binding:2,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'comparison'}},{binding:3,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'float',viewDimension:'2d-array'}},{binding:4,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'float',viewDimension:'2d-array'}},{binding:5,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'filtering'}},{binding:6,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'float',viewDimension:'2d-array'}},{binding:7,visibility:GPUShaderStage.FRAGMENT,texture:{sampleType:'float',viewDimension:'2d-array'}},{binding:8,visibility:GPUShaderStage.FRAGMENT,sampler:{type:'filtering'}}]});
  this.basicGroup=d.createBindGroup({layout:basicLayout,entries:[{binding:0,resource:{buffer:this.uniform}}]});this.mainGroup=d.createBindGroup({layout:mainLayout,entries:[{binding:0,resource:{buffer:this.uniform}},{binding:1,resource:this.shadowArrayView},{binding:2,resource:this.sampler},{binding:3,resource:this.materials.colorView},{binding:4,resource:this.materials.surfaceView},{binding:5,resource:this.materials.sampler},{binding:6,resource:this.authored.colorView},{binding:7,resource:this.authored.surfaceView},{binding:8,resource:this.authored.sampler}]});
  this.shadowUniforms=[0,1,2].map(()=>d.createBuffer({size:this.frame.byteLength,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST}));this.shadowGroups=this.shadowUniforms.map(buffer=>d.createBindGroup({layout:shadowLayout,entries:[{binding:0,resource:{buffer}},{binding:6,resource:this.authored.colorView},{binding:8,resource:this.authored.sampler}]}));
  const modules=[];for(const code of [WGSL_MAIN,WGSL_SKY,WGSL_SHADOW]){const module=d.createShaderModule({code});const info=await module.getCompilationInfo();const errors=info.messages.filter(m=>m.type==='error');if(errors.length)throw new Error(errors.map(m=>`${m.lineNum}:${m.linePos} ${m.message}`).join('\n'));modules.push(module);}
  const mainPipelineLayout=d.createPipelineLayout({bindGroupLayouts:[mainLayout]}),basicPipelineLayout=d.createPipelineLayout({bindGroupLayouts:[basicLayout]});
  this.pipeline=await d.createRenderPipelineAsync({layout:mainPipelineLayout,vertex:{module:modules[0],entryPoint:'vs',buffers:VERTEX_LAYOUT},fragment:{module:modules[0],entryPoint:'fs',targets:[{format:this.sceneFormat},{format:'rgba16float'}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less'},multisample:{count:this.samples}});
  this.foliagePipeline=await d.createRenderPipelineAsync({layout:mainPipelineLayout,vertex:{module:modules[0],entryPoint:'vs',buffers:VERTEX_LAYOUT},fragment:{module:modules[0],entryPoint:'fs',targets:[{format:this.sceneFormat},{format:'rgba16float'}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less'},multisample:{count:this.samples,alphaToCoverageEnabled:true}});
  this.particlePipeline=await d.createRenderPipelineAsync({layout:mainPipelineLayout,vertex:{module:modules[0],entryPoint:'vs',buffers:VERTEX_LAYOUT},fragment:{module:modules[0],entryPoint:'fs',targets:[{format:this.sceneFormat,blend:{color:{srcFactor:'src-alpha',dstFactor:'one-minus-src-alpha'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha'}}},{format:'rgba16float',writeMask:0}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth32float',depthWriteEnabled:false,depthCompare:'less'},multisample:{count:this.samples}});
  this.reactivePipeline=await d.createRenderPipelineAsync({layout:mainPipelineLayout,vertex:{module:modules[0],entryPoint:'vs',buffers:VERTEX_LAYOUT},fragment:{module:modules[0],entryPoint:'fs',targets:[null,{format:'rgba16float',writeMask:GPUColorWrite.ALPHA,blend:{color:{operation:'min',srcFactor:'one',dstFactor:'one'},alpha:{operation:'min',srcFactor:'one',dstFactor:'one'}}}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth32float',depthWriteEnabled:false,depthCompare:'less'},multisample:{count:this.samples}});
  this.skyPipeline=await d.createRenderPipelineAsync({layout:basicPipelineLayout,vertex:{module:modules[1],entryPoint:'vs'},fragment:{module:modules[1],entryPoint:'fs',targets:[{format:this.sceneFormat},{format:'rgba16float',writeMask:0}]},primitive:{topology:'triangle-list'},depthStencil:{format:'depth32float',depthWriteEnabled:false,depthCompare:'always'},multisample:{count:this.samples}});
  this.shadowPipeline=await d.createRenderPipelineAsync({layout:d.createPipelineLayout({bindGroupLayouts:[shadowLayout]}),vertex:{module:modules[2],entryPoint:'vs',buffers:VERTEX_LAYOUT},fragment:{module:modules[2],entryPoint:'fs',targets:[]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth32float',depthWriteEnabled:true,depthCompare:'less',depthBias:1,depthBiasSlopeScale:1.5}});
  this.kind='WebGPU';this.adapterInfo=adapter.info?`${adapter.info.vendor||''} ${adapter.info.architecture||''}`.trim():'WebGPU adapter';
 }
 async initGL(){const g=this.canvas.getContext('webgl2',{alpha:false,antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});if(!g)throw new Error('This browser does not expose WebGPU or WebGL 2. Enable hardware acceleration and reload.');this.gl=g;this.kind='WebGL 2';this.canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;this.onError('Graphics context lost. Reload to recover.');});
  this.post.initGL(g,(vs,fs)=>this.compileGL(vs,fs));await Promise.all([this.materials.initialize(null,g),this.authored.initialize(null,g)]);const compatible=s=>this.post.hdr?s:s.replace('#version 300 es','#version 300 es\n#define RAILBOUND_LDR_SCENE');this.glMain=this.compileGL(GLSL_MAIN_VS,compatible(GLSL_MAIN_FS));this.glSky=this.compileGL(GLSL_SKY_VS,compatible(GLSL_SKY_FS));this.glShadow=this.compileGL(GLSL_SHADOW_VS,GLSL_SHADOW_FS);
  this.uniform=g.createBuffer();g.bindBuffer(g.UNIFORM_BUFFER,this.uniform);g.bufferData(g.UNIFORM_BUFFER,this.frame.byteLength,g.DYNAMIC_DRAW);g.bindBufferBase(g.UNIFORM_BUFFER,0,this.uniform);
  for(const program of [this.glMain,this.glSky,this.glShadow]){const index=g.getUniformBlockIndex(program,'Frame');if(index!==g.INVALID_INDEX)g.uniformBlockBinding(program,index,0);}
  this.shadowTexture=g.createTexture();g.bindTexture(g.TEXTURE_2D_ARRAY,this.shadowTexture);g.texImage3D(g.TEXTURE_2D_ARRAY,0,g.DEPTH_COMPONENT24,this.shadowSize,this.shadowSize,3,0,g.DEPTH_COMPONENT,g.UNSIGNED_INT,null);
  for(const [key,value] of [[g.TEXTURE_MIN_FILTER,g.LINEAR],[g.TEXTURE_MAG_FILTER,g.LINEAR],[g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE],[g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE],[g.TEXTURE_COMPARE_MODE,g.COMPARE_REF_TO_TEXTURE],[g.TEXTURE_COMPARE_FUNC,g.LEQUAL]])g.texParameteri(g.TEXTURE_2D_ARRAY,key,value);
  this.shadowFBs=[0,1,2].map(i=>{const fb=g.createFramebuffer();g.bindFramebuffer(g.FRAMEBUFFER,fb);g.framebufferTextureLayer(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,this.shadowTexture,0,i);g.drawBuffers([g.NONE]);g.readBuffer(g.NONE);if(g.checkFramebufferStatus(g.FRAMEBUFFER)!==g.FRAMEBUFFER_COMPLETE)throw new Error('Cascade framebuffer unavailable');return fb;});g.bindFramebuffer(g.FRAMEBUFFER,null);this.shadowFB=this.shadowFBs[1];

  g.useProgram(this.glMain);g.uniform1i(g.getUniformLocation(this.glMain,'shadowTex'),0);g.enable(g.DEPTH_TEST);g.disable(g.CULL_FACE);this.emptyVAO=g.createVertexArray();this.materials.bindGL(this.glMain);this.authored.bindGL(this.glMain);
 }
 compileGL(vs,fs){const g=this.gl,p=g.createProgram();for(const [type,source] of [[g.VERTEX_SHADER,vs],[g.FRAGMENT_SHADER,fs]]){const s=g.createShader(type);g.shaderSource(s,source);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(s));g.attachShader(p,s);g.deleteShader(s);}g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(p));return p;}
 resize(){const rect=this.canvas.getBoundingClientRect();const scale=Math.min(globalThis.devicePixelRatio||1,this.settings.quality==='ultra'?2:1.5)*this.settings.resolution;const max=this.device?.limits.maxTextureDimension2D||4096;const [w,h]=targetSize(rect.width,rect.height,scale,max);if(w===this.width&&h===this.height)return;this.width=this.canvas.width=w;this.height=this.canvas.height=h;this.post.resize(w,h);if(this.device){this.colorMSAA?.destroy();this.geometryMSAA?.destroy();this.depth?.destroy();this.colorMSAA=this.device.createTexture({size:[w,h],format:this.sceneFormat,sampleCount:this.samples,usage:GPUTextureUsage.RENDER_ATTACHMENT});this.geometryMSAA=this.device.createTexture({label:'Normal, radial depth and indirect share MSAA',size:[w,h],format:'rgba16float',sampleCount:this.samples,usage:GPUTextureUsage.RENDER_ATTACHMENT});this.depth=this.device.createTexture({size:[w,h],format:'depth32float',sampleCount:this.samples,usage:GPUTextureUsage.RENDER_ATTACHMENT});}}
 updateUniforms(camera,world,env,train,time){const gpu=this.kind==='WebGPU',fov=(camera.fov||56)*Math.PI/180;const projection=perspective(fov,this.width/this.height,.15,15000,gpu),view=lookAt(camera.position,camera.target);this.vp=mat4Mul(projection,view);this.unjitteredVP=this.vp.slice();const jitter=this.post.temporal.prepare(this,camera,this.unjitteredVP,world,env,this.sceneKey);projection[8]+=jitter[0]*2/this.width;projection[9]+=jitter[1]*2/this.height;this.vp=mat4Mul(projection,view);this.post.temporal.setProjection(this.vp);this.frame.set(this.vp,0);this.frustum=[];for(const [axis,sign] of [[0,1],[0,-1],[1,1],[1,-1],[2,-1]]){const plane=[this.vp[3]+sign*this.vp[axis],this.vp[7]+sign*this.vp[4+axis],this.vp[11]+sign*this.vp[8+axis],this.vp[15]+sign*this.vp[12+axis]],n=Math.hypot(plane[0],plane[1],plane[2]);this.frustum.push(plane.map(x=>x/n));}this.frame.set(mat4Inverse(this.vp),16);
  const angle=(env.hour-6)/24*Math.PI*2;const altitude=Math.sin(angle);const day=smooth(-.13,.16,altitude);const sun=norm([Math.cos(angle)*.72,Math.max(.08,altitude),.38]);const target=train&&camera.mode!=='free'?train.cursor.pose(-train.length*.32).p:camera.target;const shadowTarget=[...target];this.shadowCenter=shadowTarget;
  this.cascadeMatrices=SHADOW_EXTENTS.map(extent=>stabilizedShadow(shadowTarget,sun,extent,this.shadowSize,gpu));this.frame.set(this.cascadeMatrices[1],32);this.frame.set(this.cascadeMatrices[0],88);this.frame.set(this.cascadeMatrices[2],104);this.frame.set([this.materials.ready&&this.settings.surfaces!==false?1:0,this.settings.normalMapping===false?0:1,.65,shadowCascadeCount(this.settings.quality)],120);this.frame.set([...camera.position,time],48);this.frame.set([...sun,day],52);const warm=1-smooth(.08,.65,altitude);this.frame.set([1,.98-warm*.13,.90-warm*.26,env.exposure||1],56);const w=WEATHER[env.weather]||WEATHER.clear;this.frame.set([...hex(world.sky).slice(0,3),w.fog],60);this.frame.set([w.cloud,w.wet,['alpine','coast','nordic','canyon','sakura','highland','pine','metro'].indexOf(world.theme),world.water],64);
  if(train){const head=train.cursor.pose(train.stock.locoLength*.5);this.frame.set([head.p[0],head.p[1]+2.4,head.p[2],train.controls.headlights?14:0],68);this.frame.set([...head.f,this.settings.shadows?1:0],72);}else{this.frame.set([0,0,0,0],68);this.frame.set([0,0,1,this.settings.shadows?1:0],72);}
  this.frame.set(hex(world.ground),76);this.frame.set(hex(world.rock),80);this.frame.set([this.width,this.height,env.weather==='snow'?world.railY-15:world.snowLine,w.wind],84);
 }
 visible(b,camera,shadow=false){if(!b.count)return false;if(shadow){return b.castShadow&&length(sub(b.center,this.shadowCenter))<b.radius+340;}const delta=sub(b.center,camera.position),dist=length(delta);if(this.frustum.some(p=>p[0]*b.center[0]+p[1]*b.center[1]+p[2]*b.center[2]+p[3]<-b.radius))return false;const qualityRange=this.settings.quality==='low'?.62:this.settings.quality==='medium'?.8:1;const limit=b.maxDistance<9000?b.maxDistance*qualityRange:b.maxDistance;if(dist>b.radius+limit)return false;if(dist>b.radius+30){const facing=dot(delta,norm(sub(camera.target,camera.position)));if(facing< -b.radius)return false;}return true;}
 ensureGPU(b){const d=this.device,geo=b.geometry;if(!geo.gpu){const vb=d.createBuffer({size:geo.vertices.byteLength,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST}),ib=d.createBuffer({size:geo.indices.byteLength,usage:GPUBufferUsage.INDEX|GPUBufferUsage.COPY_DST});d.queue.writeBuffer(vb,0,geo.vertices);d.queue.writeBuffer(ib,0,geo.indices);geo.gpu={vb,ib};this.geometries.add(geo);}const bytes=b.count*96;if(!b.gpuBuffer||b.capacity<bytes){b.gpuBuffer?.destroy();b.capacity=Math.max(96,bytes*2);b.gpuBuffer=d.createBuffer({size:b.capacity,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST});b.dirty=true;this.batches.add(b);}if(b.dirty&&bytes){d.queue.writeBuffer(b.gpuBuffer,0,b.data.buffer,b.data.byteOffset,bytes);b.dirty=false;}}
 ensureGL(b){const g=this.gl,geo=b.geometry;if(!geo.gl){const vb=g.createBuffer(),ib=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,vb);g.bufferData(g.ARRAY_BUFFER,geo.vertices,g.STATIC_DRAW);g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,ib);g.bufferData(g.ELEMENT_ARRAY_BUFFER,geo.indices,g.STATIC_DRAW);geo.gl={vb,ib};this.geometries.add(geo);}const bytes=b.count*96;if(!b.glBuffer||b.capacity<bytes){if(b.glBuffer)g.deleteBuffer(b.glBuffer);if(b.vao)g.deleteVertexArray(b.vao);b.glBuffer=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b.glBuffer);b.capacity=Math.max(96,bytes*2);g.bufferData(g.ARRAY_BUFFER,b.capacity,b.dynamic?g.DYNAMIC_DRAW:g.STATIC_DRAW);b.dirty=true;b.vao=g.createVertexArray();g.bindVertexArray(b.vao);g.bindBuffer(g.ARRAY_BUFFER,geo.gl.vb);for(const [loc,size,offset] of [[0,3,0],[1,3,12],[2,2,24]]){g.enableVertexAttribArray(loc);g.vertexAttribPointer(loc,size,g.FLOAT,false,32,offset);}g.bindBuffer(g.ARRAY_BUFFER,b.glBuffer);for(let i=0;i<6;i++){g.enableVertexAttribArray(i+3);g.vertexAttribPointer(i+3,4,g.FLOAT,false,96,i*16);g.vertexAttribDivisor(i+3,1);}g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,geo.gl.ib);g.bindVertexArray(null);this.batches.add(b);}if(b.dirty&&bytes){g.bindBuffer(g.ARRAY_BUFFER,b.glBuffer);g.bufferSubData(g.ARRAY_BUFFER,0,b.data.subarray(0,b.count*24));b.dirty=false;}}
 drawGPU(pass,b){pass.setVertexBuffer(0,b.geometry.gpu.vb);pass.setVertexBuffer(1,b.gpuBuffer);pass.setIndexBuffer(b.geometry.gpu.ib,'uint32');pass.drawIndexed(b.geometry.indices.length,b.count);this.drawCalls++;this.triangles+=b.geometry.indices.length/3*b.count;}
 render(batches,camera,world,env,train,time){
  if(this.lost)return;this.resize();this.sceneKey=batches[0];this.updateUniforms(camera,world,env,train,time);this.drawCalls=0;this.triangles=0;
  const visible=[],cascades=[[],[],[]],layers=shadowCascadeCount(this.settings.quality)===1?[1]:[0,1,2];
  for(const b of batches){
   const distance=length(sub(b.center,camera.position)),lodScale=this.settings.quality==='low'?.35:this.settings.quality==='medium'?.65:1;
   if((b.lodNear&&distance>b.lodNear*lodScale)||(b.lodFar&&distance<=b.lodFar*lodScale))continue;
   if(this.visible(b,camera))visible.push(b);
   if(this.settings.shadows&&b.castShadow&&b.count){const d=length(sub(b.center,this.shadowCenter));for(const i of layers)if(d<b.radius+SHADOW_EXTENTS[i]*1.6+90)cascades[i].push(b);}
  }
  visible.sort((a,b)=>Number(!!a.transparent)-Number(!!b.transparent)||(a.transparent?length(sub(b.center,camera.position))-length(sub(a.center,camera.position)):0));
  const need=new Set([...visible,...cascades.flat()]);this.shadowDrawCalls=0;
  this.post.occlusion.prepare(this,camera,this.post.options.occlusion,this.settings.quality);
  if(this.device){
   for(const b of need)this.ensureGPU(b);const d=this.device;d.queue.writeBuffer(this.uniform,0,this.frame);const encoder=d.createCommandEncoder();
   if(this.settings.shadows)for(const i of layers){
    const shadowFrame=this.frame.slice();shadowFrame.set(this.cascadeMatrices[i],32);d.queue.writeBuffer(this.shadowUniforms[i],0,shadowFrame);
    const pass=encoder.beginRenderPass({label:'Shadow cascade '+i,colorAttachments:[],depthStencilAttachment:{view:this.shadowViews[i],depthClearValue:1,depthLoadOp:'clear',depthStoreOp:'store'}});
    pass.setPipeline(this.shadowPipeline);pass.setBindGroup(0,this.shadowGroups[i]);for(const b of cascades[i]){this.drawGPU(pass,b);this.shadowDrawCalls++;}pass.end();
   }
   const pass=encoder.beginRenderPass({label:'Linear scene and geometry',colorAttachments:[
    {view:this.colorMSAA.createView(),resolveTarget:this.post.scene.createView(),clearValue:{r:.2,g:.3,b:.4,a:1},loadOp:'clear',storeOp:'discard'},
    {view:this.geometryMSAA.createView(),resolveTarget:this.post.geometry.createView(),clearValue:{r:0,g:0,b:0,a:0},loadOp:'clear',storeOp:'store'}
   ],depthStencilAttachment:{view:this.depth.createView(),depthClearValue:1,depthLoadOp:'clear',depthStoreOp:'store'}});
   pass.setPipeline(this.skyPipeline);pass.setBindGroup(0,this.basicGroup);pass.draw(3);pass.setBindGroup(0,this.mainGroup);
   for(const b of visible){pass.setPipeline(b.transparent?this.particlePipeline:b.cutout?this.foliagePipeline:this.pipeline);this.drawGPU(pass,b);}pass.end();
   if(this.post.temporal.active&&visible.some(b=>b.transparent)){const reactive=encoder.beginRenderPass({label:'Transparent temporal rejection',colorAttachments:[null,{view:this.geometryMSAA.createView(),resolveTarget:this.post.geometry.createView(),loadOp:'load',storeOp:'discard'}],depthStencilAttachment:{view:this.depth.createView(),depthLoadOp:'load',depthStoreOp:'discard'}});reactive.setPipeline(this.reactivePipeline);reactive.setBindGroup(0,this.mainGroup);for(const b of visible)if(b.transparent)this.drawGPU(reactive,b);reactive.end();}
   this.post.occlusion.encodeGPU(encoder);this.post.encodeGPU(encoder,this.context.getCurrentTexture().createView(),env,time,this.settings.quality);d.queue.submit([encoder.finish()]);
  }else{
   const g=this.gl;for(const b of need)this.ensureGL(b);
   const draw=b=>{g.bindVertexArray(b.vao);g.drawElementsInstanced(g.TRIANGLES,b.geometry.indices.length,g.UNSIGNED_INT,0,b.count);this.drawCalls++;this.triangles+=b.geometry.indices.length/3*b.count;};
   g.enable(g.DEPTH_TEST);g.depthMask(true);g.depthFunc(g.LESS);g.disable(g.BLEND);g.bindBuffer(g.UNIFORM_BUFFER,this.uniform);
   if(this.settings.shadows)for(const i of layers){
    const shadowFrame=this.frame.slice();shadowFrame.set(this.cascadeMatrices[i],32);g.bufferSubData(g.UNIFORM_BUFFER,0,shadowFrame);
    g.bindFramebuffer(g.FRAMEBUFFER,this.shadowFBs[i]);g.viewport(0,0,this.shadowSize,this.shadowSize);g.clear(g.DEPTH_BUFFER_BIT);g.useProgram(this.glShadow);this.authored.bindGL(this.glShadow);g.enable(g.POLYGON_OFFSET_FILL);g.polygonOffset(1.5,1);for(const b of cascades[i]){draw(b);this.shadowDrawCalls++;}g.disable(g.POLYGON_OFFSET_FILL);
   }
   g.bufferSubData(g.UNIFORM_BUFFER,0,this.frame);g.bindFramebuffer(g.FRAMEBUFFER,this.post.sceneFB);g.viewport(0,0,this.width,this.height);
   const opaqueBuffers=this.post.hdr?[g.COLOR_ATTACHMENT0,g.COLOR_ATTACHMENT1]:[g.COLOR_ATTACHMENT0];g.drawBuffers(opaqueBuffers);
   g.clearBufferfv(g.COLOR,0,new Float32Array([.25,.4,.6,1]));if(this.post.hdr)g.clearBufferfv(g.COLOR,1,new Float32Array(4));g.clear(g.DEPTH_BUFFER_BIT);
   g.drawBuffers([g.COLOR_ATTACHMENT0]);g.useProgram(this.glSky);g.bindVertexArray(this.emptyVAO);g.depthMask(false);g.disable(g.DEPTH_TEST);g.drawArrays(g.TRIANGLES,0,3);
   g.depthMask(true);g.enable(g.DEPTH_TEST);g.useProgram(this.glMain);this.materials.bindGL(this.glMain);this.authored.bindGL(this.glMain);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D_ARRAY,this.shadowTexture);
   for(const b of visible){
    if(b.transparent){g.drawBuffers([g.COLOR_ATTACHMENT0]);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA);g.depthMask(false);}
    else{g.drawBuffers(opaqueBuffers);g.disable(g.BLEND);g.depthMask(true);}
    if(b.cutout)g.enable(g.SAMPLE_ALPHA_TO_COVERAGE);else g.disable(g.SAMPLE_ALPHA_TO_COVERAGE);draw(b);
   }
   if(this.post.temporal.active&&visible.some(b=>b.transparent)){g.drawBuffers([g.NONE,g.COLOR_ATTACHMENT1]);g.colorMask(false,false,false,true);g.enable(g.BLEND);g.blendEquation(g.MIN);g.blendFunc(g.ONE,g.ONE);g.depthMask(false);for(const b of visible)if(b.transparent)draw(b);g.colorMask(true,true,true,true);g.blendEquation(g.FUNC_ADD);}
   g.disable(g.SAMPLE_ALPHA_TO_COVERAGE);g.disable(g.BLEND);g.depthMask(true);g.bindVertexArray(null);this.post.drawGL(env,time,this.settings.quality);
  }
  this.drawCalls+=this.post.passCount+this.post.occlusion.passCount+this.post.temporal.passCount;
 }

 disposeBatch(b){if(b.gpuBuffer)b.gpuBuffer.destroy();if(b.glBuffer)this.gl?.deleteBuffer(b.glBuffer);if(b.vao)this.gl?.deleteVertexArray(b.vao);b.gpuBuffer=b.glBuffer=b.vao=null;b.capacity=0;b.dirty=true;this.batches.delete(b);}
 disposeGeometry(geo){if(geo.gpu){geo.gpu.vb.destroy();geo.gpu.ib.destroy();geo.gpu=null;}if(geo.gl){this.gl.deleteBuffer(geo.gl.vb);this.gl.deleteBuffer(geo.gl.ib);geo.gl=null;}this.geometries.delete(geo);}
 disposeWorld(batches,sharedGeometry){for(const b of batches){this.disposeBatch(b);if(!sharedGeometry.has(b.geometry))this.disposeGeometry(b.geometry);}}
 dispose(){if(this.disposed)return;this.disposed=true;this.lost=true;for(const b of [...this.batches])this.disposeBatch(b);for(const g of [...this.geometries])this.disposeGeometry(g);this.materials.dispose();this.authored.dispose();this.post.dispose();if(this.device){for(const r of [this.uniform,...this.shadowUniforms||[],this.shadowTexture,this.colorMSAA,this.geometryMSAA,this.depth])r?.destroy();this.context?.unconfigure();this.device.destroy();}else if(this.gl){const g=this.gl;g.deleteBuffer(this.uniform);g.deleteTexture(this.shadowTexture);for(const fb of this.shadowFBs||[])g.deleteFramebuffer(fb);for(const p of [this.glMain,this.glSky,this.glShadow])g.deleteProgram(p);g.deleteVertexArray(this.emptyVAO);}}

}
