import {foundation,buildingFoundation,buildViaducts} from './cinematic-models.js';
import {buildShoreline} from './world-life.js';
import {TerrainField, GENERATOR_VERSION} from './generation.js';
import {buildExpeditionTerrain, buildEcosystem, buildLandmarks, buildCivilEngineering} from './world-detail.js';
import {clamp,lerp,smooth,fbm,noise2,rng,hex,add,sub,mul,norm,cross,frameMatrix,transform,mat4Mul,pointTransform,TAU} from './math.js';
import {Geometry,MeshBuilder,SceneBuilder,PRIMITIVES} from './geometry.js';
import {RailNetwork} from './tracks.js';
import {makeStations} from './physics.js';
const C={rail:hex('#a0a4a0'),railSide:hex('#5f6663'),tie:hex('#837d6d'),ballast:hex('#8e9187'),concrete:hex('#c2beb0'),dark:hex('#333b38'),trunk:hex('#584b3b'),lamp:hex('#ffde9b')};
export class RailwayWorld {
 constructor(def,editor={},preparedTerrain=null){this.def=def;this.editor={seed:def.seed,generationVersion:GENERATOR_VERSION,generation:{relief:1,vegetation:1,erosion:.65},objects:[],heightEdits:[],stations:[],customTrack:null,electrified:true,...editor};this.seed=this.editor.seed;this.terrain=this.editor.generationVersion===2?null:(preparedTerrain||new TerrainField(def,this.seed,this.editor.generation).prepare());this.network=new RailNetwork(def,this.editor.customTrack,{seed:this.seed,generationVersion:this.editor.generationVersion,terrain:this.terrain,generation:this.editor.generation});this.stations=makeStations(this.network,def,this.editor.stations);this.batches=[];this.signals=[];this.viewpoints=[];this.features={bridges:0,trees:0,buildings:0,shrubs:0,flowers:0,landmarks:0,cuttings:0};this.builder=new SceneBuilder();this.heightCache=new Map();this.random=rng(this.seed);}
 static async create(def,editor={}) {
  if(editor.generationVersion===2||typeof Worker==='undefined'||globalThis.RAILBOUND_STANDALONE)return new RailwayWorld(def,editor);
  const terrain=new TerrainField(def,editor.seed||def.seed,editor.generation);
  try {
   const data=await new Promise((resolve,reject)=>{
    const worker=new Worker('src/generation-worker.js',{type:'module'});
    const timer=setTimeout(()=>{worker.terminate();reject(new Error('Terrain worker timed out'));},30000);
    const finish=(fn,value)=>{clearTimeout(timer);worker.terminate();fn(value);};
    worker.onmessage=e=>e.data.error?finish(reject,new Error(e.data.error)):finish(resolve,e.data);
    worker.onerror=e=>finish(reject,new Error(e.message));
    worker.postMessage({def,seed:terrain.seed,options:terrain.options});
   });
   terrain.heights=data.heights;terrain.flow=data.flow;terrain.stats=data.stats;terrain.execution='worker';
  } catch {terrain.prepare();}
  return new RailwayWorld(def,editor,terrain);
 }
 baseHeight(x,z){if(this.terrain){let h=this.terrain.height(x,z);for(const e of this.editor.heightEdits){const d=Math.hypot(x-e.x,z-e.z)/e.radius;if(d<1)h+=e.delta*(1-d*d)**2;}return h;}const w=this.def,r=Math.hypot(x/w.rx,z/w.rz);const n=fbm(x*.00065,z*.00065,this.seed),detail=fbm(x*.004,z*.004,this.seed+43,3);const bank=smooth(.72,1.13,r);let h=w.water-16+bank*68;const mountain=smooth(1.05,1.72,r);let ridge=Math.pow(Math.abs(n-.48)*2.3,.8)*.60+detail*.42;h+=mountain*ridge*w.mountains;h+=bank*(detail-.45)*18;
  if(w.theme==='canyon'){h=w.water-18+bank*86+mountain*(Math.floor(n*11)/11*.6+detail*.3)*w.mountains;}
  if(w.theme==='metro')h=w.water-8+bank*35+mountain*n*120;
  if(w.theme==='sakura')h=w.water-8+bank*42+mountain*ridge*w.mountains;
  for(const e of this.editor.heightEdits){const d=Math.hypot(x-e.x,z-e.z)/e.radius;if(d<1)h+=e.delta*(1-d*d)**2;}
  return h;
 }
 height(x,z){let h=this.baseHeight(x,z);const near=this.network.nearest(x,z,this.terrain?70:38);if(near){const bridge=near.p[1]-h>13;if(!bridge){const target=near.p[1]-.38;h=lerp(target,h,smooth(this.terrain?14:4,this.terrain?60:32,near.distance));}}
  for(const st of this.stations){const p=this.network.edges.get(st.edge).at(st.s-60),dx=x-p.p[0],dz=z-p.p[2];const along=dx*p.f[0]+dz*p.f[2],across=dx*p.right[0]+dz*p.right[2];if(across>1&&across<100&&Math.abs(along)<150){const t=smooth(100,150,Math.abs(along))*1+smooth(55,100,across);h=lerp(p.p[1]-.4,h,clamp(t,0,1));}}
  return h;
 }
 async build(onProgress=()=>{}){onProgress('Shaping terrain',.12);await new Promise(r=>setTimeout(r,0));if(this.terrain)await buildExpeditionTerrain(this,onProgress);else this.buildTerrain();onProgress('Laying rail and bridges',.36);await new Promise(r=>setTimeout(r,0));this.buildTracks();if(this.terrain)buildCivilEngineering(this,false);onProgress('Building stations and villages',.56);await new Promise(r=>setTimeout(r,0));this.buildStations();this.buildTownscapes();onProgress('Planting forests',.73);await new Promise(r=>setTimeout(r,0));if(this.terrain){await buildEcosystem(this,onProgress);buildLandmarks(this);}else this.buildVegetation();this.buildDecorations();this.buildWater();buildShoreline(this);this.batches=this.builder.finish();onProgress('Preparing the railway',.92);return this;}
 buildTerrain(){const b=this.builder,w=this.def,span=Math.max(w.rx,w.rz)*2.8,chunk=span/8,N=24;for(let iz=-8;iz<8;iz++)for(let ix=-8;ix<8;ix++){const verts=[],inds=[],x0=ix*chunk,z0=iz*chunk,step=chunk/N;for(let z=0;z<=N;z++)for(let x=0;x<=N;x++){const wx=x0+x*step,wz=z0+z*step,h=this.height(wx,wz);const e=5,n=norm([this.height(wx-e,wz)-this.height(wx+e,wz),2*e,this.height(wx,wz-e)-this.height(wx,wz+e)]);verts.push(wx,h,wz,...n,wx*.01,wz*.01);}for(let z=0;z<N;z++)for(let x=0;x<N;x++){const i=z*(N+1)+x;inds.push(i,i+N+1,i+1,i+1,i+N+1,i+N+2);}const center=[x0+chunk/2,this.baseHeight(x0+chunk/2,z0+chunk/2),z0+chunk/2];const batch=b.mesh(new Geometry(verts,inds),center,chunk*1.8,[1,.95,0,0]);batch.maxDistance=15000;}}
 buildWater(){const w=this.def,b=this.builder;const mesh=new MeshBuilder();const s=this.terrain?this.terrain.half:Math.max(w.rx,w.rz)*2.5;mesh.quad([-s,w.water,s],[s,w.water,s],[s,w.water,-s],[-s,w.water,-s],[0,1,0]);const batch=b.mesh(mesh.geometry(),[0,w.water,0],s*1.5,[2,.12,.1,0],hex(w.waterColor));batch.castShadow=false;batch.maxDistance=14000;}
 railCross(p,offset,y){return [p.p[0]+p.right[0]*offset,p.p[1]+y,p.p[2]+p.right[2]*offset];}
 buildTracks(){const b=this.builder,w=this.def;const electrified=this.editor.electrified;
  for(const edge of this.network.edges.values()){
   const n=Math.ceil(edge.length/3);const pieces=new Map();const getChunk=s=>{const c=Math.floor(s/210);if(!pieces.has(c))pieces.set(c,{rail:new MeshBuilder(),bed:new MeshBuilder(),center:edge.at(s).p});return pieces.get(c);};
   for(let i=0;i<n;i++){const s=i/n*edge.length,t=(i+1)/n*edge.length,p=edge.at(s),q=edge.at(t),chunk=getChunk(s);chunk.bed.quad(this.railCross(p,-2.25,-.22),this.railCross(q,-2.25,-.22),this.railCross(q,2.25,-.22),this.railCross(p,2.25,-.22),[0,1,0]);for(const side of [-1,1]){const off=side*.7175;const r0=this.railCross(p,off-.038,.19),r1=this.railCross(q,off-.038,.19),r2=this.railCross(q,off+.038,.19),r3=this.railCross(p,off+.038,.19);chunk.rail.quad(r0,r1,r2,r3,[0,1,0]);chunk.rail.quad(this.railCross(p,off-.031,.025),this.railCross(q,off-.031,.025),r1,r0);chunk.rail.quad(r3,r2,this.railCross(q,off+.031,.025),this.railCross(p,off+.031,.025));}
   }
   for(const c of pieces.values()){const bed=b.mesh(c.bed.geometry(),c.center,180,[7,.96,0,0],C.ballast);bed.maxDistance=5800;const rail=b.mesh(c.rail.geometry(),c.center,180,[0,.26,.85,0],C.rail);rail.maxDistance=4800;}
   for(let s=0;s<edge.length;s+=.86){const p=edge.at(s);b.oriented('box',frameMatrix(add(p.p,[0,-.015,0]),p.f,[2.7,.19,.25]),C.tie,[0,.96,0,0]);}
   if(electrified){for(let s=0;s<edge.length;s+=54){const p=edge.at(s),q=edge.at(Math.min(s+54,edge.length));const pole=this.railCross(p,-3.2,3.7);b.oriented('box',frameMatrix(pole,p.f,[.16,7.4,.17]),C.railSide,[0,.55,.5,0]);b.oriented('box',frameMatrix(this.railCross(p,-1.65,6.35),p.f,[3.5,.12,.13]),C.railSide,[0,.55,.5,0]);b.segment(this.railCross(p,-3.1,7.0),this.railCross(p,-.3,6.35),.065,C.railSide);b.instance('cylinder',this.railCross(p,-.1,6.15),[.16,.36,.16],hex('#4b544b'),[0,.45,.1,0]);b.segment(this.railCross(p,0,5.92),this.railCross(q,0,5.92),.027,C.dark,[0,.3,.5,0]);b.segment(this.railCross(p,0,6.65),this.railCross(q,0,6.65),.02,C.dark);b.segment(this.railCross(p,0,5.92),this.railCross(p,0,6.65),.022,C.dark);}}
   for(let s=360;s<edge.length-35;s+=400){const p=edge.at(s),pos=this.railCross(p,3.3,0);b.instance('cylinder',add(pos,[0,2.6,0]),[.14,5.2,.14],C.railSide);b.oriented('box',frameMatrix(add(pos,[0,5.1,0]),p.f,[.62,1.64,.25]),C.dark);this.signals.push({edge:edge.id,s,pos: add(pos,[0,5.1,0]),f:p.f});}
  }
  buildViaducts(this);this.buildJunction();this.buildGallery();
 }
 buildJunction(){const b=this.builder,p=this.network.edges.get('approach').at(this.network.edges.get('approach').length-12);b.oriented('box',frameMatrix(this.railCross(p,2.8,.18),p.f,[1.1,.36,.65]),hex('#827b66'));b.instance('cylinder',this.railCross(p,3.5,.7),[.07,1.2,.07],C.dark);b.oriented('box',frameMatrix(this.railCross(p,3.5,1.4),p.f,[.58,.32,.12]),hex('#e9c568'));}
 buildGallery(){const b=this.builder,w=this.def;if(['metro','sakura','coast'].includes(w.theme))return;const edge=this.network.edges.get('main'),start=edge.length*.46;for(let s=start;s<start+90;s+=6){const p=edge.at(s);b.oriented('box',frameMatrix(add(p.p,[0,6.3,0]),p.f,[9,1.5,6.15]),hex('#aaa89b'),[6,.95,0,0]);for(const side of [-1,1])b.oriented('box',frameMatrix(this.railCross(p,side*3.65,2.7),p.f,[.8,5.8,.85]),hex('#aaa89b'),[6,.95,0,0]);if(w.theme==='alpine'||w.theme==='nordic')b.oriented('box',frameMatrix(this.railCross(p,-4.2,3.6),p.f,[1.2,7.7,6.15]),hex(w.rock),[6,.96,0,0]);}}
 buildStations(){const b=this.builder,w=this.def;for(const st of this.stations){const edge=this.network.edges.get(st.edge);for(let ds=-st.platform;ds<14;ds+=7){const p=edge.at(st.s+ds);b.oriented('box',frameMatrix(this.railCross(p,4.7,.34),p.f,[5.8,1.1,7.1]),C.concrete,[6,.95,0,0]);b.oriented('box',frameMatrix(this.railCross(p,2.02,.905),p.f,[.3,.025,7.05]),hex('#d5be66'));b.oriented('box',frameMatrix(this.railCross(p,7.34,.95),p.f,[.1,.18,7.05]),hex('#a2a399'));}
   for(let ds=-140;ds<-25;ds+=12){const p=edge.at(st.s+ds);b.oriented('box',frameMatrix(this.railCross(p,5.1,5.2),p.f,[6.8,.23,12.12]),w.theme==='metro'?hex('#89909b'):hex('#717d75'),[0,.7,.25,0]);b.oriented('box',frameMatrix(this.railCross(p,6.5,3),p.f,[.18,4.4,.18]),C.dark,[0,.55,.4,0]);b.oriented('box',frameMatrix(this.railCross(p,4.4,4.96),p.f,[.22,.1,3]),C.lamp,[4,.5,0,2.5]);}
   for(let ds=-155;ds<10;ds+=28){const p=edge.at(st.s+ds);b.instance('cylinder',this.railCross(p,7.6,3.7),[.12,5.6,.12],C.dark);b.instance('sphere',this.railCross(p,7.6,6.5),[.42,.35,.42],C.lamp,[4,.4,0,1.2]);}
   const p=edge.at(st.s-92),yaw=Math.atan2(p.f[0],p.f[2]);this.buildHouse(this.railCross(p,16.4,0),[12,7.8,32],yaw,true);b.oriented('box',frameMatrix(this.railCross(p,12,3),p.f,[.16,2.7,5.5]),hex('#263b3f'));b.oriented('box',frameMatrix(this.railCross(p,2.4,2.15),p.f,[.12,1.05,.6]),hex('#e4e2cf'));b.oriented('box',frameMatrix(this.railCross(p,2.4,2.14),p.f,[.13,.75,.42]),hex('#42534f'));
   for(let ds=-110;ds<-30;ds+=32){const pp=edge.at(st.s+ds);b.oriented('box',frameMatrix(this.railCross(pp,6.1,1.5),pp.f,[.75,.13,2.1]),hex('#675a46'));for(const z of [-.65,.65]){const pp2=edge.at(st.s+ds+z);b.oriented('box',frameMatrix(this.railCross(pp2,6.1,1.18),pp2.f,[.62,.65,.08]),C.dark);} }
   for(let i=0;i<9;i++){const pp=edge.at(st.s-25-i*11);this.buildPerson(this.railCross(pp,3.1+(i%3)*.8,1.01),i);}
  }}
 buildPerson(p,seed){const b=this.builder;const colors=['#4c687a','#a28872','#667663','#9b5851','#3d454d'];b.instance('cylinder',add(p,[0,.68,0]),[.42,.82,.30],hex(colors[seed%colors.length]));b.instance('sphere',add(p,[0,1.27,0]),[.29,.35,.29],hex('#c9a98b'));for(const side of [-1,1])b.instance('box',add(p,[side*.11,.22,0]),[.14,.47,.17],C.dark);}
 buildHouse(p,size,yaw=0,station=false){p=buildingFoundation(this,p,size,yaw,station);const b=this.builder,w=this.def,[sx,sy,sz]=size;const stone=['highland','alpine','nordic'].includes(w.theme);const bodyColor=station?hex('#d9cfb4'):hex(stone?'#c3c0ad':w.theme==='canyon'?'#c1a084':'#d0c7b3');const base=transform(p,[1,1,1],yaw);const part=(pos,scale,col,props=[0,.86,0,0],roll=0)=>b.oriented('box',mat4Mul(base,transform(pos,scale,0,0,roll)),col,props);
  part([0,sy*.5,0],[sx,sy,sz],bodyColor,[6,.96,0,0]);const roofColor=hex(w.theme==='nordic'?'#615c59':w.theme==='sakura'?'#525b5a':w.theme==='highland'?'#5f635e':'#7a6250');part([-sx*.265,sy+sx*.12,0],[sx*.58,.24,sz+1],roofColor,[0,.85,0,0],.42);part([sx*.265,sy+sx*.12,0],[sx*.58,.24,sz+1],roofColor,[0,.85,0,0],-.42);
  for(const side of [-1,1])for(let z=-sz*.35;z<=sz*.35;z+=Math.max(2.8,sz/7)){part([side*(sx*.5+.03),sy*.52,z],[.05,sy*.27,1.35],hex('#435c61'),[3,.18,.2,0]);part([side*(sx*.5+.08),sy*.37,z],[.15,.08,1.55],hex('#e0dac6'));}
  for(const end of [-1,1])for(const x of [-sx*.27,sx*.27]){part([x,sy*.58,end*(sz*.5+.035)],[1.45,1.8,.08],hex('#3d5358'),[3,.26,.15,0]);part([x,sy*.58,end*(sz*.5+.082)],[.065,1.82,.035],hex('#d7d0bd'));part([x,sy*.58,end*(sz*.5+.084)],[1.46,.065,.035],hex('#d7d0bd'));part([x,sy*.58-.94,end*(sz*.5+.09)],[1.66,.10,.20],hex('#d2cbb6'));}
  for(const side of [-1,1]){part([side*(sx*.5+.13),sy-.08,0],[.14,.18,sz+.4],hex('#4a504a'),[0,.8,.25,0]);part([side*(sx*.5+.02),.23,0],[.08,.46,sz],hex('#a29e8e'),[6,.9,0,0]);}
  part([0,sy*.32,sz*.5+.03],[sx*.17,sy*.60,.07],hex('#5d675c'));part([sx*.27,sy+sx*.32,sz*.27],[1,2.7,1.1],hex('#92897b'));this.features.buildings++;}
 buildTownscapes(){const b=this.builder,w=this.def,r=this.random;for(const st of this.stations){const origin=this.network.edges.get(st.edge).at(st.s-60);const yaw=Math.atan2(origin.f[0],origin.f[2]);const count=w.theme==='metro'?64:w.theme==='canyon'?12:25;for(let i=0;i<count;i++){const along=(r()-.5)*600,across=35+r()*290;const p=add(add(origin.p,mul(origin.f,along)),mul(origin.right,across));p[1]=this.height(p[0],p[2]);if(p[1]<w.water+3)continue;const size=[7+r()*8,4.5+r()*5,8+r()*11];if(w.theme==='metro'){size[0]=18+r()*23;size[1]=20+r()**2*160;size[2]=18+r()*22;this.buildTower(p,size,yaw);}else {const rotation=yaw+(r()-.5)*.3;if(foundation(this,p,size,rotation).spread>size[1]*.75)continue;if(this.network.nearest(p[0],p[2],Math.hypot(size[0],size[2])*.55+7))continue;this.buildHouse(p,size,rotation);}}
   for(let ds=-230;ds<200;ds+=12){const pp=add(add(origin.p,mul(origin.f,ds)),mul(origin.right,29));pp[1]=this.height(pp[0],pp[2])+.05;b.oriented('box',frameMatrix(pp,origin.f,[7,.08,12.1]),hex('#676c66'),[6,.97,0,0]);b.oriented('box',frameMatrix(add(pp,[0,.047,0]),origin.f,[.12,.01,4]),hex('#d0cbbb'));}
   for(let i=0;i<7;i++){const pp=add(add(origin.p,mul(origin.f,-70+i*12)),mul(origin.right,23));pp[1]=this.height(pp[0],pp[2]);this.buildCar(pp,yaw,i);}
  }
  if(w.theme==='sakura'){for(let i=0;i<120;i++){const x=(r()-.5)*w.rx*3,z=(r()-.5)*w.rz*3,h=this.height(x,z);if(h<w.water+8||h>w.railY+25)continue;b.instance('box',[x,h+.08,z],[30,.13,55],hex(i%2?'#98ad66':'#7c9a60'),[6,.95,0,0]);}}
  if(w.theme==='coast'){const p=this.network.edges.get('return').at(400);const pos=add(p.p,mul(p.right,55));pos[1]=this.height(pos[0],pos[2]);b.instance('cylinder',add(pos,[0,12,0]),[6,24,6],hex('#e6dfcb'));b.instance('cylinder',add(pos,[0,24,0]),[7.5,2,7.5],hex('#9d5a4c'));b.instance('cylinder',add(pos,[0,27,0]),[4.2,4,4.2],hex('#d1dccb'),[3,.25,.2,0]);b.instance('cone',add(pos,[0,30,0]),[7,3,7],hex('#654a41'));}
 }
 buildTower(p,size,yaw){p=buildingFoundation(this,p,size,yaw);const b=this.builder,[sx,sy,sz]=size;const base=transform(p,[1,1,1],yaw);b.oriented('box',mat4Mul(base,transform([0,sy*.5,0],size)),hex('#555f69'),[3,.4,.2,0]);for(let y=3;y<sy;y+=3.3){for(const side of [-1,1]){b.oriented('box',mat4Mul(base,transform([side*(sx/2+.04),y,0],[.13,.17,sz+.1])),hex('#869398'));for(let z=-sz/2+2;z<sz/2;z+=3.6){const lit=((y*5+z*3+sx)|0)%4!==0;b.oriented('box',mat4Mul(base,transform([side*(sx/2+.09),y+1.25,z],[.025,1.7,2.2])),lit?hex('#ccb987'):hex('#2b414e'),[lit?4:3,.3,.1,lit?1.25:0]);}}}this.features.buildings++;}
 buildCar(p,yaw,index){const b=this.builder,base=transform(p,[1,1,1],yaw);const color=hex(['#bdc3bf','#455c67','#894e43','#b9ac8f'][index%4]);b.oriented('body',mat4Mul(base,transform([0,.8,0],[1.75,.8,4.2])),color,[0,.3,.5,0]);b.oriented('body',mat4Mul(base,transform([0,1.35,-.12],[1.52,.8,2.35])),hex('#35474b'),[3,.2,.3,0]);for(const x of [-.85,.85])for(const z of [-1.25,1.25])b.oriented('cylinder',mat4Mul(base,transform([x,.43,z],[.6,.18,.6],0,0,Math.PI*.5)),C.dark);}
 buildVegetation(){const w=this.def,r=this.random,b=this.builder;const desired=Math.round(w.trees*1.65);let placed=0;for(let tries=0;tries<desired*6&&placed<desired;tries++){const x=(r()-.5)*w.rx*4,z=(r()-.5)*w.rz*4;const h=this.height(x,z);if(h<w.water+2||h>w.snowLine+20)continue;const near=this.network.nearest(x,z,22);if(near&&near.distance<8)continue;let stationArea=false;for(const st of this.stations){const p=this.network.edges.get(st.edge).at(st.s-65);const d=sub([x,h,z],p.p),side=d[0]*p.right[0]+d[2]*p.right[2],along=d[0]*p.f[0]+d[2]*p.f[2];if(side>-32&&side<38&&Math.abs(along)<180)stationArea=true;}if(stationArea)continue;const h1=this.baseHeight(x+8,z),h2=this.baseHeight(x,z+8);if(Math.abs(h1-h)>17||Math.abs(h2-h)>17)continue;if(noise2(x*.005,z*.005,this.seed)<.26)continue;
  const scale=10+r()*14;this.tree([x,h,z],scale,r());placed++;}
  this.features.trees=placed;
  for(let i=0;i<130;i++){const edge=[...this.network.edges.values()][i%4],p=edge.at(r()*edge.length),pos=add(p.p,mul(p.right,(r()>.5?1:-1)*(18+r()*75)));pos[1]=this.height(pos[0],pos[2]);if(pos[1]<w.water)continue;b.instance('sphere',add(pos,[0,1.4,0]),[3+r()*7,2+r()*4,3+r()*6],hex(w.rock),[6,.95,0,0],r()*TAU);}
 }
 tree(p,height,variation=.5){const b=this.builder,w=this.def;const snow=w.theme==='nordic'&&p[1]>120;const trunkHeight=height*.78;
  if(w.theme==='canyon'){b.instance('cylinder',add(p,[0,height*.14,0]),[.4,height*.28,.4],hex('#6a7a50'));b.instance('sphere',add(p,[0,height*.27,0]),[2.5,2,2.5],hex('#7f895b'),[5,.9,0,0]);return;}
  b.instance('cylinder',add(p,[0,trunkHeight*.5,0]),[height*.036,trunkHeight,height*.036],C.trunk,[0,.98,0,0]);const broad=['sakura','pine','coast','metro'].includes(w.theme)&&variation>.35;
  if(broad){const color=hex(w.theme==='sakura'&&variation>.64?'#cda3af':variation>.7?'#718252':'#4f7454');for(let i=0;i<3;i++)b.instance('foliage',add(p,[(i-1)*height*.16,height*(.66+i*.09),Math.sin(i*3)*height*.14]),[height*.55,height*.51,height*.54],color,[5,.95,0,0]);}
  else{const color=snow?hex('#afbcba'):hex(variation>.5?'#385c48':'#446950');b.instance('pine',add(p,[0,height*.12,0]),[height*.5,height*.9,height*.5],color,[5,.95,0,0],variation*TAU);}
 }
 buildDecorations(){for(const o of this.editor.objects){const p=[o.x,this.height(o.x,o.z),o.z];if(o.type==='tree')this.tree(p,o.size||18,.7);else if(o.type==='building')this.buildHouse(p,[12,8,15],o.rotation||0);else if(o.type==='rock')this.builder.instance('sphere',add(p,[0,3,0]),[9,6,8],hex(this.def.rock),[6,.94,0,0]);}}
}
